config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "searches#index"
  
  resources :watcheds
  resources :watched_shows
  resources :favorites
  resources :want_movies
  resources :want_shows

  post "assign" => "watcheds#assign"
  post "shown" => "watcheds#shown"
  post "favorite" => "watcheds#favorite"
  post "list_movie" => "want_movies#list_movie"
  post "list_show" => "want_shows#list_show"
  post "watch_movie" => "want_movies#watch_movie"
  post "watch_show" => "want_shows#watch_show"
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @user = User.find(current_user.id)
    @favs = Favorite.where(user_id: current_user.id)
    Tmdb::Api.key(ENV["movie_db_key"])

    @configuration = Tmdb::Configuration.new
    @configuration.base_url
    @configuration.poster_sizes
    @configuration.profile_sizes

  end

  def show
    @fav = Favorite.find(params[:id])
    Tmdb::Api.key(ENV["movie_db_key"])

    @configuration = Tmdb::Configuration.new
    @configuration.base_url
    @configuration.poster_sizes
    @configuration.profile_sizes
  end

  def edit
    @fav = Favorite.find(params[:id])

  end

  def update
    @fav = Favorite.find(params[:id])
    if @fav.update(fav_params)
      redirect_to favorites_path
    else
      render edit_favorite_path
    end

  end

  def destroy
    @fav = Favorite.find(params[:id])
    @fav.destroy
    redirect_to "/favorites"

  end

  private
  def fav_params
    params.require(:favorite).permit(:user_id, :title, :overview, :notes, :poster)
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/edit.html.erb
<h2>Edit Favorite</h2>
<%= form_for @fav do |f| %>
<%= f.text_field :notes %>
<%= f.submit "update notes"%>
<% end %>

<%= link_to "delete favorite", favorite_path, method: :delete%>

app/views/favorites/index.html.erb
<center><h2><%=@user.username%>'s Favorites</h2></center>
<% @array = [] %>

<% @favs.each do |f| %>
<% @array.push(f.title) %>
<%end%>

<center><b>Random Favorite:</b> <%= @array.sample() %></center>
<hr>
<div class="pop_wrap">
<% @favs.each do |f|%>
<div class="pop">
<a href="/favorites/<%=f.id%>"><%= f.title %></a><br>
<%= image_tag (@configuration.base_url+@configuration.poster_sizes[2]+f.poster) %>
</div>
<% end %>
</div>

app/views/favorites/show.html.erb
<center><h2><%= @fav.title %></h2></center>
<div class="watched_movies">
<%= image_tag (@configuration.base_url+@configuration.poster_sizes[2]+@fav.poster) %>
<b>Overview:</b> <%= @fav.overview%><br>
<b>Notes:</b> <%= @fav.notes%><hr>
<%= link_to "Add Notes", edit_favorite_path %> •
<%= link_to "Go Back", :back %></div>