config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "searches#index"
  
  resources :watcheds
  resources :watched_shows
  resources :favorites
  resources :want_movies
  resources :want_shows

  post "assign" => "watcheds#assign"
  post "shown" => "watcheds#shown"
  post "favorite" => "watcheds#favorite"
  post "list_movie" => "want_movies#list_movie"
  post "list_show" => "want_shows#list_show"
  post "watch_movie" => "want_movies#watch_movie"
  post "watch_show" => "want_shows#watch_show"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Screen Time</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('tv-icon.png'), :rel => 'icon', :type =>  'image/png' %>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,600|Alice|Playfair+Display" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">


  </head>

  <nav>
    <div class="links">
    <a href="http://themoviedb.org"><%= image_tag("tmdblogo.png", {:style => "width:25px;margin-top:-5px;"}) %></a>  
    <div class="link"><i class="fa fa-film"></i>
    <%= link_to "home", root_path %></div>
    <% if signed_in? %>
    <div class="link"><i class="fa fa-list"></i></div>
    <%= link_to "want to watch", want_movies_path%>
    <div class="link"><i class="fa fa-check-circle"></i>
    <%= link_to "watched", watcheds_path %></div>
    <div class="link"><i class="fa fa-heart"></i>
    <%= link_to "favorites", favorites_path%></div>
    <div class="link"><i class="fa fa-power-off"></i>
    <%= link_to "sign out",destroy_user_session_path, method: :delete %></div>

    <% end%>

    <% if !signed_in? %>
    <div class="link"><i class="fa fa-user-plus"></i>
    <%= link_to "sign up", new_user_registration_path%></div>
    <div class="link"><i class="fa fa-user-circle"></i>
    <%= link_to "sign in", new_user_session_path %></div>
    <% end %></div>

    <div class="searchbar"><%= form_tag("/", method: "get") do %>
    <%= text_field_tag(:q)%>
    <%= submit_tag("search")%>
    <% end %></div>
  </nav>

  <body>
<div class="content">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %></div>
  </body>

</html>